// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PAC.Producao.Data;

#nullable disable

namespace PAC.Producao.Data.Migrations
{
    [DbContext(typeof(ProducaoContext))]
    partial class ProducaoContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("PAC.Producao.Models.Operario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Apelido")
                        .HasColumnType("VARCHAR(128)");

                    b.Property<bool>("Ativo")
                        .HasColumnType("BIT");

                    b.Property<byte?>("Cargo")
                        .HasColumnType("TINYINT");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("VARCHAR(128)");

                    b.Property<byte?>("PeriodoTrabalho")
                        .HasColumnType("TINYINT");

                    b.HasKey("Id");

                    b.ToTable("Operarios", "Producao");
                });
#pragma warning restore 612, 618
        }
    }
}
